<?xml version="1.0"?>

<robot name="eureca" xmlns:xacro="http://www.ros.org/wiki/xacro" xmlns:gz="http://gazebosim.org/schema">

  <!-- <xacro:include filename="$(find lampo_description)/urdf/sweepee/camera.urdf.xacro" /> -->

  <xacro:property name="M_PI" value="3.14159"/>


  <!-- Base Size -->
  <xacro:property name="base_x_size" value="1.02" />
  <xacro:property name="base_y_size" value="0.55" />
  <xacro:property name="base_z_size" value="0.35" />
  

  <xacro:macro name="sweepee" params="prefix *origin">
  
    <!-- Base footprint is on the ground under the robot -->
    <link name="${prefix}base_footprint">
    </link>  


    <!-- Base link is the center of the robot's bottom plate -->
    <link name="${prefix}base_link_sweepee">
      <visual>
        <origin xyz="0 0 0.032" rpy="0 0 -${M_PI/2}" />
        <geometry>
          <mesh filename="file://$(find lampo_description)//meshes/sweepee/visual/sweepee.dae"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0" />
        </material>
      </visual>
      <inertial>
          <origin xyz="0 0 0.2" rpy="0 0 0" />
          <mass value="150" />
          <inertia ixx="2.0" ixy="0.0" ixz="0.0" iyy="3.7" iyz="0.0" izz="6.0" />
      </inertial>
      <collision>
        <origin xyz="0 0 0.2" rpy="0 0 0" />
        <geometry>
          <box size="0.3 ${base_y_size} 0.05"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}base_footprint_joint" type="fixed">
      <xacro:insert_block name="origin"/> 
      <parent link="${prefix}base_footprint" />
      <child link="${prefix}base_link_sweepee" />
    </joint>

    <link name="${prefix}front_laser" />
    <joint name="${prefix}front_laser_joint" type="fixed">
      <origin xyz="${base_x_size/2-0.15} 0.0 ${base_z_size/2+0.085}" rpy="0 0 0" />
      <parent link="${prefix}base_link_sweepee" />
      <child link="${prefix}front_laser" />
    </joint>

      <link name="${prefix}rear_laser" />
    <joint name="${prefix}rear_laser_joint" type="fixed">
      <origin xyz="${-base_x_size/2+0.15} 0.0 ${base_z_size/2+0.085}" rpy="0 0 ${M_PI}" />
      <parent link="${prefix}base_link_sweepee" />
      <child link="${prefix}rear_laser" />
    </joint>

      <link name='${prefix}front_left_wheel'>
        <inertial>
          <mass value="1"/>
          <inertia ixx="0.145"  ixy="0"  ixz="0" iyy="0.145" iyz="0" izz="0.125" />
        </inertial>
        <visual>
          <geometry>
            <sphere length="0.05" radius="0.1"/>
          </geometry>
        </visual>
        <collision>
          <geometry>
            <sphere length="0.05" radius="0.1"/>
          </geometry>
        </collision>
      </link>

      <link name='${prefix}rear_left_wheel'>
        <inertial>
          <mass value="1"/>
          <inertia ixx="0.145"  ixy="0"  ixz="0" iyy="0.145" iyz="0" izz="0.125" />
        </inertial>
        <visual>
          <geometry>
            <sphere length="0.05" radius="0.1"/>
          </geometry>
        </visual>
        <collision>
          <geometry>
            <sphere length="0.05" radius="0.1"/>
          </geometry>
        </collision>
      </link>

      <link name='${prefix}front_right_wheel'>
        <inertial>
          <mass value="1"/>
          <inertia ixx="0.145"  ixy="0"  ixz="0" iyy="0.145" iyz="0" izz="0.125" />
        </inertial>
        <visual>
          <geometry>
            <sphere length="0.05" radius="0.1"/>
          </geometry>
        </visual>
        <collision>
          <geometry>
            <sphere length="0.05" radius="0.1"/>
          </geometry>
        </collision>
      </link>

      <link name='${prefix}rear_right_wheel'>
        <inertial>
          <mass value="1"/>
          <inertia ixx="0.145"  ixy="0"  ixz="0" iyy="0.145" iyz="0" izz="0.125" />
        </inertial>
        <visual>
          <geometry>
            <sphere length="0.05" radius="0.1"/>
          </geometry>
        </visual>
        <collision>
          <geometry>
            <sphere length="0.05" radius="0.1"/>
          </geometry>
        </collision>
      </link>

      <gazebo reference="${prefix}front_left_wheel">
        <mu1>1.0</mu1>
        <mu2>0.0</mu2>
        <fdir1 gz:expressed_in='${prefix}base_footprint'>1 -1 0</fdir1>
      </gazebo>

      <gazebo reference="${prefix}rear_left_wheel">
        <mu1>1.0</mu1>
        <mu2>0.0</mu2>
        <fdir1 gz:expressed_in='${prefix}base_footprint'>1 1 0</fdir1>
      </gazebo>

      <gazebo reference="${prefix}front_right_wheel">
        <mu1>1.0</mu1>
        <mu2>0.0</mu2>
        <fdir1 gz:expressed_in='${prefix}base_footprint'>1 1 0</fdir1>
      </gazebo>

        <gazebo reference="${prefix}rear_right_wheel">
        <mu1>1.0</mu1>
        <mu2>0.0</mu2>
        <fdir1 gz:expressed_in='${prefix}base_footprint'>1 -1 0</fdir1>
      </gazebo>


      <joint name='${prefix}front_left_wheel_joint' type='revolute'>
        <origin xyz="0.3 0.25 0.1" rpy="-1.5707 0 0"/>
        <parent link="${prefix}base_link_sweepee"/>
        <child link="${prefix}front_left_wheel"/>
        <axis xyz="0 0 1"/>
        <limit effort="10000.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="5.1"/>
      </joint>

      <joint name='${prefix}front_right_wheel_joint' type='revolute'>
        <origin xyz="0.3 -0.25 0.1" rpy="-1.5707 0 0"/>
        <parent link="${prefix}base_link_sweepee"/>
        <child link="${prefix}front_right_wheel"/>
        <axis xyz="0 0 1"/>
        <limit effort="10000.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="5.1"/>
      </joint>

      <joint name='${prefix}rear_left_wheel_joint' type='revolute'>
        <origin xyz="-0.3 0.25 0.1" rpy="-1.5707 0 0"/>
        <parent link="${prefix}base_link_sweepee"/>
        <child link="${prefix}rear_left_wheel"/>
        <axis xyz="0 0 1"/>
        <limit effort="10000.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="5.1"/>
      </joint>

      <joint name='${prefix}rear_right_wheel_joint' type='revolute'>
        <origin xyz="-0.3 -0.25 0.1" rpy="-1.5707 0 0"/>
        <parent link="${prefix}base_link_sweepee"/>
        <child link="${prefix}rear_right_wheel"/>
        <axis xyz="0 0 1"/>
        <limit effort="10000.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="5.1"/>
      </joint>


  <gazebo reference="${prefix}front_laser">
    <sensor name='gpu_lidar' type='gpu_lidar'>"
        <pose relative_to='${prefix}front_laser'>0 0 0 0 0 0</pose>
        <topic>${prefix}lidar</topic>
        <update_rate>10</update_rate>
        <ray>
            <scan>
                <horizontal>
                    <samples>640</samples>
                    <resolution>1</resolution>
                    <min_angle>-1.396263</min_angle>
                    <max_angle>1.396263</max_angle>
                </horizontal>
                <vertical>
                    <samples>1</samples>
                    <resolution>0.01</resolution>
                    <min_angle>0</min_angle>
                    <max_angle>0</max_angle>
                </vertical>
            </scan>
            <range>
                <min>0.08</min>
                <max>10.0</max>
                <resolution>0.01</resolution>
            </range>
        </ray>
        <always_on>1</always_on>
        <visualize>true</visualize>
    </sensor>
  </gazebo>

  <gazebo>
    <plugin
      filename="gz-sim-mecanum-drive-system"
      name="gz::sim::systems::MecanumDrive">
      <front_left_joint>${prefix}front_left_wheel_joint</front_left_joint>
      <front_right_joint>${prefix}front_right_wheel_joint</front_right_joint>
      <back_left_joint>${prefix}rear_left_wheel_joint</back_left_joint>
      <back_right_joint>${prefix}rear_right_wheel_joint</back_right_joint>
      <wheel_separation>0.5</wheel_separation>
      <wheelbase>0.7</wheelbase>
      <wheel_radius>0.1</wheel_radius>
      <min_acceleration>-5</min_acceleration>
      <max_acceleration>5</max_acceleration>
      <topic>${prefix}cmd_vel</topic>
      <frame_id>${prefix}base_link_sweepee</frame_id>

    </plugin>
  </gazebo>

  </xacro:macro>


</robot>
