sweepee_2:
  controller_manager:
    ros__parameters:
      update_rate: 50  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      imm:
        type: imm_controller/ImmController

      cartesian_motion_controller:
        type: cartesian_motion_controller/CartesianMotionController

      position_controller:
            type: position_controllers/JointGroupPositionController

  position_controller:
    ros__parameters:
      joints:
        - sweepee_2/shoulder_pan_joint
        - sweepee_2/shoulder_lift_joint
        - sweepee_2/elbow_joint
        - sweepee_2/wrist_1_joint
        - sweepee_2/wrist_2_joint
        - sweepee_2/wrist_3_joint

  cartesian_motion_controller:
    ros__parameters:
      end_effector_link: "sweepee_2/tool0"
      robot_base_link: "sweepee_2/base_link"
      target_frame_topic: "sweepee_2/target_frame"
      robot_description: 'sweepee_2/robot_description'
      joints:
        - sweepee_2/shoulder_pan_joint
        - sweepee_2/shoulder_lift_joint
        - sweepee_2/elbow_joint
        - sweepee_2/wrist_1_joint
        - sweepee_2/wrist_2_joint
        - sweepee_2/wrist_3_joint

      command_interfaces:
        - position
          #- velocity

      solver:
          error_scale: 1.0
          iterations: 10
          
      pd_gains:
          trans_x: {p: 10.0}
          trans_y: {p: 10.0}
          trans_z: {p: 10.0}
          rot_x: {p: 1.0}
          rot_y: {p: 1.0}
          rot_z: {p: 1.0}

  joint_trajectory_controller:
    ros__parameters:
      joints:
        - sweepee_2/shoulder_pan_joint
        - sweepee_2/shoulder_lift_joint
        - sweepee_2/elbow_joint
        - sweepee_2/wrist_1_joint
        - sweepee_2/wrist_2_joint
        - sweepee_2/wrist_3_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      constraints:
        stopped_velocity_tolerance: 0.2
        goal_time: 0.0
        shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
        shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
        elbow_joint: { trajectory: 0.2, goal: 0.1 }
        wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
        wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
        wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

  imm:
    ros__parameters:
      command_joints:
        - sweepee_2/shoulder_pan_joint
        - sweepee_2/shoulder_lift_joint
        - sweepee_2/elbow_joint
        - sweepee_2/wrist_1_joint
        - sweepee_2/wrist_2_joint
        - sweepee_2/wrist_3_joint
      joints:
        - sweepee_2/shoulder_pan_joint
        - sweepee_2/shoulder_lift_joint
        - sweepee_2/elbow_joint
        - sweepee_2/wrist_1_joint
        - sweepee_2/wrist_2_joint
        - sweepee_2/wrist_3_joint
      control_interface:
      - position
      state_interface:
      - position
      - velocity
      robot_chain_root: sweepee_2/base_link
      robot_chain_tip:  sweepee_2/tool0
      amr_base_link:  sweepee_2/base_footprint
      cmd_vel_topic: /sweepee_2/cmd_vel
      only_robot: true
      omni: true

